spring:
  application:
    name: ms-users
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/dv_parksystem
    username: root
    password: Lifeinmono77
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://parksystem-mysql:3306/dv_parksystem
    username: root
    password: Lifeinmono77
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: America/Lima
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 9000

jwt:
  secret: ynnZnUmVsXjHBgtOZQuRCiIMeQHPfqXwePYXwiYLIgwsBlvjZe
  expiration: 86400000

app:
  security:
    basic:
      username: parksystem_api
      password: ParkSystem2024!SecureAPI

logging:
  level:
    com.cibertec: DEBUG
    org.springframework.security: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
