name: DEPLOY-FRONTEND-REACT

on:
  push:
    branches:
      - main
    paths:
      - "frontend-react/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend-react/package-lock.json

      - name: Create env file
        working-directory: frontend-react
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          if [ -n "$ENV_FILE" ]; then
            echo "$ENV_FILE" | base64 --decode > .env
          else
            echo "ENV_FILE secret not found, creating empty .env file"
            touch .env
          fi

      - name: Install dependencies (npm)
        working-directory: frontend-react
        run: npm ci

      - name: Run Lint
        working-directory: frontend-react
        run: npm run lint

      - name: Type Check
        working-directory: frontend-react
        run: npm run check

      - name: Build React App
        working-directory: frontend-react
        run: npm run build

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: "mayor"
          minor_pattern: "feat"
          format: "${major}.${minor}.${increment}"
        id: version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build Docker Image
        env:
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          docker build -t $PROJECT_NAME:$NEW_VERSION ./frontend-react
          docker build -t $PROJECT_NAME:latest ./frontend-react

      - name: Push Docker Image
        env:
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          docker push $PROJECT_NAME:$NEW_VERSION
          docker push $PROJECT_NAME:latest
